# Generated by Django 5.2.17 on 2026-09-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='21 Void Technologies', max_length=200)),
                ('tagline', models.CharField(default='Fusing Technology With Market Intelligence', max_length=250)),
                ('phone', models.CharField(default='+263 77 123 4567', max_length=50)),
                ('email', models.EmailField(default='info@21void.com', max_length=254)),
                ('address', models.TextField(default='Harare, Zimbabwe')),
                ('currency_symbol', models.CharField(default='$', max_length=10)),
                ('currency_code', models.CharField(default='USD', max_length=10)),
                ('receipt_header_note', models.CharField(default='Official Purchase Receipt', max_length=250)),
                ('receipt_footer_note', models.TextField(default='Thank you for doing business with 21 Void Technologies! All products guaranteed authentic.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Setting',
                'verbose_name_plural': 'Company Settings',
            },
        ),
    ]
