# Generated by Django 5.2.17 on 2026-09-21 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification'),
        ('inventory', '0004_supplier_stock_reorder_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='notification',
            name='severity',
            field=models.CharField(choices=[('INFO', 'Informational'), ('WARNING', 'Warning / Reorder'), ('URGENT', 'Urgent Attention'), ('CRITICAL', 'Critical / Out of Stock')], default='WARNING', max_length=20),
        ),
    ]
