# Generated by Django 5.2.17 on 2026-09-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification_product_notification_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysetting',
            name='is_customized',
            field=models.BooleanField(default=False, help_text='Flag indicating company profile has been configured'),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='logo',
            field=models.ImageField(blank=True, help_text='Custom Company Logo for Receipts and Header', null=True, upload_to='company/'),
        ),
    ]
