# Generated by Django 5.2.17 on 2026-09-23 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_companysetting_is_customized_companysetting_logo'),
        ('inventory', '0005_stock_expiry_warning_days_stockbatch_expiration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='inventory.stockbatch'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LOW_STOCK', 'Low Stock Alert'), ('EXPIRING', 'Expiry Alert'), ('SYSTEM', 'System Notice'), ('EXPENSE', 'Expense Notice')], default='LOW_STOCK', max_length=30),
        ),
    ]
