# Generated by Django 5.2.17 on 2026-09-19 08:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Expense Category',
                'verbose_name_plural': 'Expense Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Description or purpose of the expense', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount spent (USD)', max_digits=12)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Date when expense was incurred')),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash (USD)'), ('EcoCash', 'EcoCash'), ('Swipe', 'Swipe / POS Card'), ('Bank Transfer', 'Bank Transfer / ZIPIT'), ('InnBucks', 'InnBucks'), ('Mukuru', 'Mukuru'), ('Other', 'Other')], default='Cash', max_length=30)),
                ('reference_number', models.CharField(blank=True, default='', help_text='Receipt, voucher or reference number', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_expenses', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.expensecategory')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
