# Generated by Django 5.2.17 on 2026-09-21 17:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='default_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Default expense amount', max_digits=12),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Whether this expense category auto-recurs periodically'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='last_recurring_date',
            field=models.DateField(blank=True, help_text='Last date an automatic recurring expense was recorded', null=True),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='recurring_interval',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', help_text='Recurring frequency interval', max_length=20),
        ),
    ]
