# Generated by Django 5.2.17 on 2026-09-23 07:37

from django.db import migrations, models


def populate_roles(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    for user in User.objects.all():
        old_role = getattr(user, 'role', None)
        if old_role:
            user.roles = [old_role]
        else:
            user.roles = ['ADMIN'] if user.is_superuser else ['STAFF']
        user.save(update_fields=['roles'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.JSONField(blank=True, default=list, help_text='List of assigned user roles'),
        ),
        migrations.RunPython(populate_roles, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
