# Generated by Django 5.2.17 on 2026-09-19 06:29

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='received_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='serial_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current Selling Price (USD)', max_digits=12)),
                ('quantity_available', models.PositiveIntegerField(default=0, help_text='Current total available quantity from active batches')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, help_text='Threshold below which stock is flagged as Low Stock')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_invoice_number', models.CharField(blank=True, db_index=True, default='', help_text='Supplier Invoice Reference / Number', max_length=100)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=150)),
                ('date_received', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='Unit Purchase Cost (USD)', max_digits=12)),
                ('quantity_received', models.PositiveIntegerField(default=1, help_text='Initial quantity received')),
                ('quantity_remaining', models.PositiveIntegerField(default=1, help_text='Quantity currently available in this batch')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='True while quantity_remaining > 0')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Stock Batch',
                'verbose_name_plural': 'Stock Batches',
                'ordering': ['date_received', 'id'],
            },
        ),
    ]
