# Generated by Django 5.2.17 on 2026-09-19 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_options_remove_product_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, default='', help_text='Size / Model Specs', max_length=100),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.stock'),
        ),
    ]
