# Generated by Django 5.2.17 on 2026-09-19 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_size_stockbatch_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('contact_person', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='stock',
            name='reorder_quantity',
            field=models.PositiveIntegerField(default=5, help_text='Reorder quantity threshold for low stock notification alerts'),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='supplier_ref',
            field=models.ForeignKey(blank=True, help_text='Direct link to registered Supplier', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='inventory.supplier'),
        ),
    ]
