# Generated by Django 5.2.17 on 2026-09-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_supplier_stock_reorder_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='expiry_warning_days',
            field=models.PositiveIntegerField(default=30, help_text='Default days before expiration to trigger stock alert'),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='expiration_date',
            field=models.DateField(blank=True, db_index=True, help_text='Batch expiration date', null=True),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='serial_number',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Serial number for serialized inventory (Qty strictly 1)', max_length=100),
        ),
    ]
