# Generated by Django 5.2.17 on 2026-09-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stock_expiry_warning_days_stockbatch_expiration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbatch',
            name='email',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Optional email / account reference for serialized item', max_length=255),
        ),
    ]
