# Generated by Django 5.2.17 on 2026-09-18 15:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_sold', models.DecimalField(decimal_places=2, help_text='Sale Price (USD)', max_digits=12)),
                ('profit', models.DecimalField(decimal_places=2, help_text='Net profit (Amount Sold - Cost Price)', max_digits=12)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash (USD)'), ('EcoCash', 'EcoCash'), ('Bank Transfer', 'Bank Transfer / ZIPIT'), ('Card', 'Credit / Debit Card')], default='Cash', max_length=30)),
                ('date_sold', models.DateField(default=django.utils.timezone.now)),
                ('invoice_number', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sales.customer')),
                ('product', models.OneToOneField(help_text='The serialized item sold (one-to-one)', on_delete=django.db.models.deletion.PROTECT, related_name='sale', to='inventory.product')),
                ('user', models.ForeignKey(help_text='Staff or Admin who recorded this sale', on_delete=django.db.models.deletion.PROTECT, related_name='processed_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'ordering': ['-date_sold', '-created_at'],
            },
        ),
    ]
