# Generated by Django 5.2.17 on 2026-09-19 06:29

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_options_remove_product_cost_price_and_more'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sale', 'verbose_name_plural': 'Sales'},
        ),
        migrations.RemoveField(
            model_name='sale',
            name='amount_sold',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='profit',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total revenue of this transaction', max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total cost of goods sold via FIFO', max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total profit (Amount - Cost)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date_sold',
            field=models.DateField(auto_now_add=True, db_index=True, help_text='Automatically captured transaction date'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash (USD)'), ('EcoCash', 'EcoCash'), ('Swipe', 'Swipe / POS Card'), ('Bank Transfer', 'Bank Transfer / ZIPIT'), ('InnBucks', 'InnBucks'), ('Mukuru', 'Mukuru')], default='Cash', max_length=30),
        ),
        migrations.AlterField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(help_text='Cashier/staff who processed the sale', on_delete=django.db.models.deletion.PROTECT, related_name='processed_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Selling price per unit (USD)', max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Line total (unit_price * quantity)', max_digits=12)),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total cost deducted via FIFO', max_digits=12)),
                ('profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Profit on this line item', max_digits=12)),
                ('serial_number', models.CharField(blank=True, default='', help_text='Optional serial number for 1:1 serialized item', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='inventory.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
            ],
            options={
                'verbose_name': 'Sale Item',
                'verbose_name_plural': 'Sale Items',
            },
        ),
        migrations.CreateModel(
            name='SaleBatchDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_deducted', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_deductions', to='inventory.stockbatch')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_deductions', to='sales.saleitem')),
            ],
            options={
                'verbose_name': 'Sale Batch Deduction',
                'verbose_name_plural': 'Sale Batch Deductions',
            },
        ),
    ]
