# Generated by Django 5.2.17 on 2026-09-19 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_options_remove_sale_amount_sold_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Cashier/staff who processed the sale', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_sales', to=settings.AUTH_USER_MODEL),
        ),
    ]
