# Generated by Django 5.2.17 on 2026-09-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_sale_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='email',
            field=models.CharField(blank=True, default='', help_text='Optional email / account reference for serialized item', max_length=255),
        ),
    ]
